### PR TITLE
feat: New Arc support

### PR DESCRIPTION
**Pull request by lodev09**
#20

### CODE REVIEW

**Comment by lodev09** [comment]
Expo 52 broke auto-linking on this library so we can no longer use it :(
Will now use the generated example from build-bob moving forward.

**Comment by lodev09** [comment]
Pretty much working on both IOS and Android in New Arch 🎉
Need some people to test it please :)

**Comment by fobos531** [comment]
Hey @lodev09 - is anything blocking this PR from being published on NPM?

**Comment by lodev09** [comment]
:rocket: _This pull request is included in v1.0.0. See [Release 1.0.0](https://github.com/lodev09/react-native-true-sheet/releases/tag/v1.0.0) for release notes._

**Pull request merged**
