### PR TITLE
add popover support for iOS

### PR DESCRIPTION
**Pull request by marcosrdz**
https://github.com/user-attachments/assets/7b4dbfdc-d3d2-47df-8856-fb77ace8d506

### CODE REVIEW

**Comment by lodev09** [comment]
Hey @marcosrdz, do you have a video showcasing this feature?

**Comment by marcosrdz** [comment]
> Hey @marcosrdz, do you have a video showcasing this feature?

Attached video

**Comment by lodev09** [comment]
I see. okay, thank you for the demo @marcosrdz.. However, I'm not sure about this. I feel like that needs to be on its own package.

TrueSheet is intended for bottom sheets and adding that option defeats that purpose. I know that iPad already handles sheet UI properly and popover is kinda something different.

Also, android needs to support something similar for consistency.

**Comment by marcosrdz** [comment]
> I see. okay, thank you for the demo @marcosrdz.. However, I'm not sure about this. I feel like that needs to be on its own package.
> 
> TrueSheet is intended for bottom sheets and adding that option defeats that purpose. I know that iPad already handles sheet UI properly and popover is kinda something different.
> 
> Also, android needs to support something similar for consistency.

Understood. Makes sense. I'll fork the package and implement these features. I'll see how Android can get the same popover experience. Thank you!

**Comment by lodev09** [comment]
@marcosrdz got it.. thank you for your contribution! Good luck :)

**Pull request closed without merging**
